![data-x](http://oi64.tinypic.com/o858n4.jpg)






# Homework 02

## Numpy Introduction


__1a) Create two numpy arrays (a and b). a should be all integers between 10-19 (inclusive), and b should be ten evenly spaced numbers between 1-7. Print all the results below:__ 


i) Square all the elements in both arrays (element-wise)  
ii)  Add both the squared arrays (e.g., [1,2] + [3,4] = [4,6])  
iii)  Sum the elements with even indices of the added array.  
iv)  Take the square root of the added array (element-wise square root)__


In [2]:
import numpy as np
a = np.arange(10,20,1);
b = np.linspace(1,7,10);
c = [];

for x in range(len(a)):
    print(np.power(a[x],2));
    
for x in range(len(b)):
    print(np.power(b[x],2));

for x in range(len(a)):
    c.insert(x,np.power(a[x],2) + np.power(b[x],2)); 
    print(np.power(a[x],2) + np.power(b[x],2));

total = 0;
for x in range(0,len(a),2):
    total = total + np.power(a[x],2) + np.power(b[x],2);

print(total);

for x in range(len(a)):
    print(np.power(c,0.5));



100
121
144
169
196
225
256
289
324
361
1.0
2.77777777778
5.44444444444
9.0
13.4444444444
18.7777777778
25.0
32.1111111111
40.1111111111
49.0
101.0
123.777777778
149.444444444
178.0
209.444444444
243.777777778
281.0
321.111111111
364.111111111
410.0
1105.0
[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]
[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]
[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]
[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]
[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]
[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.6133845

__1b) Append b to a, reshape the appended array so that it is a 5x4, 2d array and store the results in a variable called m. Print m.__


In [3]:
d = np.concatenate([a,b]);

m = np.empty((5, 4), dtype=object);
i = 0;
for x in range(0,5,1):
    for y in range(0,4,1):
        m[x][y] = d[i];
        i = i + 1;

print(m);

[[10.0 11.0 12.0 13.0]
 [14.0 15.0 16.0 17.0]
 [18.0 19.0 1.0 1.6666666666666665]
 [2.333333333333333 3.0 3.6666666666666665 4.333333333333333]
 [5.0 5.6666666666666661 6.333333333333333 7.0]]


__1c) Extract the second and the third column of the m matrix. Store the resulting 5x2 matrix in a new variable called m2. Print m2.__


In [4]:
m2 = np.empty((5, 2), dtype=object);
for x in range(0,5,1):
    for y in range(0,2,1):
        m2[x][y] = m[x][y+1];

print(m2);

[[11.0 12.0]
 [15.0 16.0]
 [19.0 1.0]
 [3.0 3.6666666666666665]
 [5.6666666666666661 6.333333333333333]]


__1d) Take the dot product of m2 and m store the results in a matrix called m3. Print m3.
Note that Dot product of two matrices A.B =A<sup>T</sup>B__

In [5]:
m3 = np.empty((5, 2), dtype=object);

m3 = np.dot(m.transpose(),m2);

print(m3);

[[697.33333333333337 402.22222222222223]
 [748.11111111111109 437.88888888888891]
 [437.88888888888891 454.55555555555554]
 [482.33333333333337 489.88888888888891]]


__1e) Round the m3 matrix to two decimal points. Store the result in place and print the new m3.__


In [32]:
for x in range(0,4,1):
    for y in range(0,2,1):
        m3[x][y] = round(m3[x][y],2);
print(m3);

[[697.33000000000004 402.22000000000003]
 [748.11000000000001 437.88999999999999]
 [437.88999999999999 454.56]
 [482.32999999999998 489.88999999999999]]


__1f) Sort the m3 array so that the highest value is at the top left, the next highest value to the right of the highest, and the lowest value is at the bottom right. Print the sorted m3 array.__


In [36]:
i = 0;
m4 = [];

for x in range(0,4,1):
    for y in range(0,2,1):
        m4.insert(i,m3[x][y])
        i= i + 1;
        
m5 = sorted(m4, reverse = True)

m6 = np.empty((4, 2), dtype=object);
i = 0;
for x in range(0,4,1):
    for y in range(0,2,1):
        m6[x][y] = m5[i];
        i = i + 1;

print(m6);

[[748.11000000000001 697.33000000000004]
 [489.88999999999999 482.32999999999998]
 [454.56 437.88999999999999]
 [437.88999999999999 402.22000000000003]]


## NumPy and Masks
__2a) create an array called 'f' where the values are sin(x) for x from 0 to pi with 100 values in f__
* print f
* use a 'mask' and print an array that is True when f >= 1/2 and False when f < 1/2
* create and print an array sequence that has only those values where f>= 1/2



In [55]:
import numpy.ma as ma

g = np.linspace(0,np.pi,100);
f = [];
msk = [];

for x in range(0,100,1):
    f.insert(x,np.sin(g[x]));
    if f[x]>=0.5:
        msk.insert(x,0);
    else:
        msk.insert(x,1);
        
mskf = ma.masked_array(f,msk);
        
print(f);
print(mskf);


[0.0, 0.031727933498067649, 0.063423919656564506, 0.095056043304182672, 0.12659245357374926, 0.15800139597334989, 0.18925124436041021, 0.22031053278654064, 0.25114798718107922, 0.28173255684142967, 0.31203344569848712, 0.34202014332566871, 0.37166245566032757, 0.40093053540661372, 0.42979491208917164, 0.45822652172741041, 0.48619673610046871, 0.51367739157340631, 0.54064081745559756, 0.56705986386277074, 0.5929079290546404, 0.61815898622060517, 0.64278760968653925, 0.66676900051629162, 0.69007901148211204, 0.71269417137886293, 0.73459170865753332, 0.75574957435425827, 0.77614646429175682, 0.7957618405308321, 0.81457595205033573, 0.8325698546347714, 0.84972542994951439, 0.86602540378443871, 0.88145336344758207, 0.89599377429133586, 0.90963199535451833, 0.92235429410458147, 0.93414786026510666, 0.94500081871466846, 0.95490224144407387, 0.96384215855994204, 0.97181156832354165, 0.97880244621477874, 0.98480775301220802, 0.98982144188093268, 0.99383846446125412, 0.99685477595194238, 0.99886

## NumPy and 2 Variable Prediction

__ Let 'x' be the number of miles a person drives per day and 'y' be the dollars spent on buying car fuel (per day).__
  
__We have created 2 numpy arrays each of size 100 that represent x and y.  
x ( number of miles) ranges from 1 to 10 with a uniform noise of (0,1/2)  
y (money spent in dollars) will be from 1 to 20 with a uniform noise (0,1)__ 


In [56]:
# seed the random number generator with a fixed value
import numpy as np
np.random.seed(500)

x=np.linspace(1,10,100)+ np.random.uniform(low=0,high=.5,size=100) 
y=np.linspace(1,20,100)+ np.random.uniform(low=0,high=1,size=100)
print ('x = ',x)
print ('y= ',y)

x =  [  1.34683976   1.12176759   1.51512398   1.55233174   1.40619168
   1.65075498   1.79399331   1.80243817   1.89844195   2.00100023
   2.3344038    2.22424872   2.24914511   2.36268477   2.49808849
   2.8212704    2.68452475   2.68229427   3.09511169   2.95703884
   3.09047742   3.2544361    3.41541904   3.40886375   3.50672677
   3.74960644   3.64861355   3.7721462    3.56368566   4.01092701
   4.15630694   4.06088549   4.02517179   4.25169402   4.15897504
   4.26835333   4.32520644   4.48563164   4.78490721   4.84614839
   4.96698768   5.18754259   5.29582013   5.32097781   5.0674106
   5.47601124   5.46852704   5.64537452   5.49642807   5.89755027
   5.68548923   5.76276141   5.94613234   6.18135713   5.96522091
   6.0275473    6.54290191   6.4991329    6.74003765   6.81809807
   6.50611821   6.91538752   7.01250925   6.89905417   7.31314433
   7.20472297   7.1043621    7.48199528   7.58957227   7.61744354
   7.6991707    7.85436822   8.03510784   7.80787781   8.22410224
   7.9

__3a) Find Expected value of x and the expected value of y__

In [57]:
ev_x = np.mean(x);
ev_y = np.mean(y);

print(ev_x);
print(ev_y);

5.78253254159
11.0129816833


__3b) Find variance of distributions of  x and  y__

In [58]:
print(np.var(x))

7.03332752948


In [59]:
print(np.var(y))

30.1139035755


__3c) Find co-variance of x and y.__

In [60]:
print(np.mean((x - ev_x)*(y-ev_y)));

14.5111663945


__3d) Assuming that number of dollars spent in car fuel is only dependant on the miles driven, by  a linear relationship.  
Write code that uses a linear predictor to calculate a predicted value of y for each x
ie y_predicted = f(x) = y0+mx.__  

In [65]:
slope = np.mean((y - ev_y)/(x - ev_x));
const = ev_y - slope * ev_x;

print(slope);
print(const);

2.01735066496
-0.652414184585


__3e) Predict y for each value in x, pur the error into an array called y_error__

In [68]:
y_pre = [];

for i in range (0,100,1):
    y_pre.insert(i,x[i]*slope + const);

y_error = y - y_pre

print(y_pre);
print(y_error);

[2.0646339079125431, 1.6105844033649053, 2.4041221848902374, 2.4791832856531841, 2.1843675262309272, 2.6777374778192238, 2.9666994105581495, 2.9837356636108909, 3.1774089526635354, 3.3843049671517473, 4.0568968753211836, 3.8346754533901635, 3.8849001975487454, 4.113949499614141, 4.3871062856311545, 5.0390775242282686, 4.7632135950731396, 4.7587139536665504, 5.5915114511419644, 5.3129700826610762, 5.5821625000626511, 5.9129246359721348, 6.2376836833224596, 6.2244593612103563, 6.4218833885129269, 6.9118568576765211, 6.7081187867818848, 6.9573274654316535, 6.53678946015033, 7.4390320957249241, 7.732314393944959, 7.5398158543367995, 7.4677688081725719, 7.9247435766647918, 7.7376968691098558, 7.9583512505173353, 8.0730439130734251, 8.3966777835942885, 9.0004215480719356, 9.1239664929009781, 9.3677417241395133, 9.812678314499367, 10.03111207861933, 10.081863948438382, 9.5703299511791862, 10.39462073022384, 10.37952247532864, 10.736285864056773, 10.435808632877356, 11.245012773386494, 10.8172

__3f) Write code that calculates the root mean square error(RMSE), that is root of average of y-error squared__

In [73]:
print(np.power(np.mean(np.power(y_error,2)),0.5));

0.435017623931
